cookingplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('users/', include('users.urls')),
    path('', include('menu.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/urls.py
from django.urls import path

from .views import MealCreateView, MealDetailView, MealsList, MealUpdateView, MealDeleteView, AddMealToDay, \
    AddIngredientsToMeal, MealIngredientsDeleteView

app_name = 'meals'

urlpatterns = [
    path('list/', MealsList.as_view(), name='list'),
    path('create/', MealCreateView.as_view(), name='create'),
    path('<slug:slug>/detail/', MealDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', MealUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', MealDeleteView.as_view(), name='delete'),
    path('<slug:slug>/add_to_day/', AddMealToDay.as_view(), name='add_to_day'),
    path('<slug:slug>/add_ingredients/', AddIngredientsToMeal.as_view(), name='add_ingredients'),
    path('<slug:slug>/delete_ingredient/<int:pk>', MealIngredientsDeleteView.as_view(), name='delete_ingredient'),
]

menu/urls.py
from django.urls import path

from .views import index, DayDeleteView, DayListView, DayCreateView, BreakfastCreateView, LaunchCreateView, \
    DinnerCreateView, ShoppingListView

app_name = 'menu'

urlpatterns = [
    path('', index, name='index'),
    path('list/', DayListView.as_view(), name='list'),
    path('create/', DayCreateView.as_view(), name='create'),
    path('<slug:slug>/create/breakfast', BreakfastCreateView.as_view(), name='create_breakfast'),
    path('<slug:slug>/create/launch', LaunchCreateView.as_view(), name='create_launch'),
    path('<slug:slug>/create/dinner', DinnerCreateView.as_view(), name='create_dinner'),
    path('<slug:slug>/delete/', DayDeleteView.as_view(), name='delete'),
    path('', ShoppingListView.as_view(), name='shopping_list'),

]

meals/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.urls import reverse
from pytils.translit import slugify

from ingredients.models import Ingredient


class MealIngredients(models.Model):
    ingredient = models.ForeignKey(Ingredient, verbose_name='Продукт', on_delete=models.CASCADE)
    qty = models.IntegerField(verbose_name='Количество')
    meal = models.ForeignKey('Meal', on_delete=models.CASCADE, related_name='meal')

    class Meta:
        unique_together = ('ingredient', 'meal')


class Meal(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    slug = models.SlugField(unique=True)
    category = models.ForeignKey('MealCategory', verbose_name="Категория", related_name="meal_cat", null=True,
                                 on_delete=models.SET_NULL)
    description = models.TextField(max_length=1000, verbose_name="Описание", blank=True)
    photo = models.ImageField(upload_to='meals', null=True, default=None, blank=True, verbose_name='Фотография')
    servings = models.SmallIntegerField(verbose_name="Кол-во порций", null=True)

    def get_absolute_url(self):
        return reverse('meals:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            print(self.slug)
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.name)


class MealCategory(models.Model):
    name = models.CharField(max_length=15, unique=True, verbose_name="Категория блюда")
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.name)

meals/forms.py
import datetime

from django import forms

from .models import Meal, MealIngredients


class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ('author', 'slug',)


class MealIngredientsForm(forms.ModelForm):
    class Meta:
        model = MealIngredients
        exclude = ('meal',)


class AddMealToDayForm(forms.Form):
    CHOICES = (('ЗАВТРАК', 'Завтрак'),
               ('ОБЕД', 'Обед'),
               ('УЖИН', 'Ужин'))
    date = forms.DateField(widget=forms.SelectDateWidget, label='Введите дату', initial=datetime.date.today())
    day_time = forms.ChoiceField(choices=CHOICES, label='Введите прием пищи')

meals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect

from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView

from menu.models import Day
from .forms import MealForm, MealIngredientsForm, AddMealToDayForm
from .models import Meal, MealIngredients, MealCategory


class AuthorMixin(UserPassesTestMixin):
    def test_func(self):
        slug = self.kwargs['slug']
        author = Meal.objects.get(slug=slug).author
        user = self.request.user
        return user == author


class MealsList(ListView):
    model = Meal
    context_object_name = 'meals'
    template_name = 'meals/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cats'] = MealCategory.objects.all()
        return context

    def get_queryset(self):
        q = self.request.GET.get('q')
        cat = self.request.GET.get('category')
        if q and cat:
            queryset = Meal.objects.filter(category__slug=cat, name__iregex=q)
        elif q:
            queryset = Meal.objects.filter(name__iregex=q)
        elif cat:
            queryset = Meal.objects.filter(category__slug=cat)
        else:
            queryset = Meal.objects.all()
        return queryset


class MealCreateView(LoginRequiredMixin, CreateView):
    model = Meal
    form_class = MealForm
    template_name = 'meals/create.html'

    def __init__(self):
        super().__init__()
        self.object = None

    def get_success_url(self):
        return reverse_lazy('meals:detail', kwargs={'slug': self.object.slug})

    def post(self, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            # slug = slugify(form.cleaned_data['name'])
            self.object = form.save(commit=False)
            self.object.author = self.request.user
            # self.object.slug = slug
            self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class MealDetailView(FormMixin, DetailView):
    model = Meal
    form_class = MealIngredientsForm
    template_name = 'meals/detail.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('meals:detail', kwargs={'slug': self.get_object().slug})

    def get_context_data(self, **kwargs):
        kwargs['ingredients'] = MealIngredients.objects.filter(meal_id=self.get_object().id)
        return super().get_context_data(**kwargs)


class AddIngredientsToMeal(AuthorMixin, FormMixin, DetailView):
    model = Meal
    form_class = MealIngredientsForm
    template_name = 'meals/detail_old.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            self.ingredient = form.save(commit=False)
            self.ingredient.meal_id = Meal.objects.get(slug=kwargs['slug']).id
            self.ingredient.save()
            return redirect(reverse_lazy('meals:detail', kwargs={'slug': kwargs['slug']}))
        else:
            return self.form_invalid(form)


class MealUpdateView(AuthorMixin, LoginRequiredMixin, UpdateView):
    model = Meal
    form_class = MealForm
    template_name = 'meals/create.html'


class MealDeleteView(AuthorMixin, LoginRequiredMixin, DeleteView):
    model = Meal
    template_name = 'meals/delete.html'
    success_url = reverse_lazy('meals:list')


class MealIngredientsDeleteView(AuthorMixin, LoginRequiredMixin, DeleteView):
    model = MealIngredients

    def get_success_url(self, **kwargs):
        return reverse_lazy('meals:detail', kwargs={'slug': self.get_object().meal.slug})


class AddMealToDay(LoginRequiredMixin, UpdateView, FormMixin):
    model = Meal
    template_name = 'meals/add_to_day.html'

    def get_context_data(self, **kwargs):
        kwargs['form'] = AddMealToDayForm()
        return super().get_context_data(**kwargs)

    def post(self, *args, **kwargs):
        form = AddMealToDayForm(self.request.POST)
        if form.is_valid():
            kwargs['date'] = form.cleaned_data['date']
            kwargs['day_time'] = form.cleaned_data['day_time']
            meal = Meal.objects.get(slug=kwargs['slug'])
            try:
                day = Day.objects.get(slug=kwargs['date'])
            except Day.DoesNotExist:
                day = Day.objects.create(date=kwargs['date'], author=self.request.user)
            if kwargs['day_time'] == 'ЗАВТРАК':
                day.breakfast = meal
            elif kwargs['day_time'] == 'ОБЕД':
                day.launch = meal
            elif kwargs['day_time'] == 'УЖИН':
                day.dinner = meal
            day.save()
            return redirect(reverse('menu:list'))
        else:
            return self.form_invalid(form)

templates/meals/add_to_day.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
        <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
            <div class="u-clearfix u-sheet u-sheet-1">
                <form method="post" enctype="multipart/form-data" action="">
                    <div>
                        {%csrf_token%}
                        {{ form|crispy }}
                    </div>
                    <button type="submit">Сохранить</button>
                </form>
            </div>
        </section>
{% endblock %}

templates/meals/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
        <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
            <div class="u-clearfix u-sheet u-sheet-1">
                <title> {{title}} </title>
                <form method="post" enctype="multipart/form-data" action="">
                    <div>
                        {%csrf_token%}
                        {{ form|crispy }}
                    </div>
                    <button type="submit">Сохранить</button>
                </form>
            </div>
        </section>
{% endblock %}

templates/meals/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="u-align-center u-clearfix u-white u-section-1" id="carousel_2a64">
        <div class="u-clearfix u-sheet u-valign-middle-xs u-sheet-1">
            <form action = "{% url 'meals:delete' meal.pk %}" method = "POST">
                {%csrf_token%}
                <p>Вы действительно хотите удалить ,блюдо "{{ meal.name }}"?</p>
                <input type = "submit"  value = "Удалить">
            </form>
        </div>
    </section>
{% endblock %}

templates/meals/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/meals/meal_detail.css' %}" media="screen">
{% endblock %}

{% block content %}
    <section class="u-align-center u-clearfix u-white u-section-1" id="carousel_2a64">
      <div class="u-clearfix u-sheet u-valign-middle-xs u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-gutter-0 u-layout">
            <div class="u-layout-row">
              <div class="u-align-left u-container-style u-layout-cell u-left-cell u-size-30 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <div class="u-container-style u-expanded-width u-group u-group-1">
                    <div class="u-container-layout u-container-layout-2">
                      <h1 class="u-text u-text-custom-color-2 u-text-1">{{meal.name}}</h1>
                      <p class="u-align-left u-text u-text-2">Автор: {{meal.author}}</p>
                    </div>
                  </div>
                    <div class="u-container-style u-expanded-width u-group u-group-5">
                        <div class="u-layout-row">
                            <a href="{% url 'meals:update' meal.slug %}" class="u-align-left u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-1">изменить</a>
                            <a href="{% url 'meals:delete' meal.slug %}" class="u-align-center u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-1">удалить</a>
                            <a href="{% url 'meals:add_to_day' meal.slug %}" class="u-align-right u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-1">+ в меню</a>
                        </div>
                    </div>
                {% if meal.description %}
                  <div class="u-container-style u-expanded-width u-group u-group-2">
                    <div class="u-container-layout u-container-layout-3">
                      <h6 class="u-text u-text-3">Описание: </h6>
                      <p class="u-text u-text-4">{{meal.description}}</p>
                    </div>
                  </div>
                {% endif %}
                  <div class="u-container-style u-expanded-width u-group u-group-3">
                    <div class="u-container-layout u-container-layout-4">
                    {% if ingredients %}
                      <h6 class="u-text u-text-5">Ингридиенты:<br>
                      </h6>
                      <div class="u-expanded-width u-table u-table-responsive u-table-1">
                        <table class="u-table-entity">
                          <colgroup>
                            <col width="25%">
                            <col width="25%">
                            <col width="25%">
                            <col width="25%">
                          </colgroup>
                          <tbody class="u-table-body">
                            <tr style="height: 46px;">
                              <th class="u-border-1 u-border-grey-dark-1 u-table-cell">Наименование</th>
                              <th class="u-border-1 u-border-grey-dark-1 u-table-cell">Ед.изм.</th>
                              <th class="u-border-1 u-border-grey-dark-1 u-table-cell">Количество</th>
                              <th class="u-border-1 u-border-grey-dark-1 u-table-cell">Удалить</th>
                            </tr>
                            {% for ingredient in ingredients %}
                            <tr style="height: 46px;">
                              <td class="u-border-1 u-border-grey-dark-1 u-table-cell">{{  ingredient.ingredient}}</td>
                              <td class="u-border-1 u-border-grey-dark-1 u-table-cell">{{  ingredient.ingredient.units}}</td>
                              <td class="u-border-1 u-border-grey-dark-1 u-table-cell">{{  ingredient.qty}}</td>
                              <td class="u-border-1 u-border-grey-dark-1 u-table-cell">
                                  <form action="{% url 'meals:delete_ingredient' meal.slug ingredient.pk %}" method="post" >
                                      {%csrf_token%}
                                      <button type="submit" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">Удалить</button>
                                  </form>
                              </td>
                            </tr>
                          {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    {% endif %}
                      <div class="u-container-style u-expanded-width u-group u-group-4">
                        <div class="u-container-layout u-container-layout-5">
                            <h6 class="u-text u-text-default u-text-6">Добавить ингридиенты:</h6>
                            <form action="{% url 'meals:add_ingredients' meal.slug %}" method="post" >
                                <div>
                                    {%csrf_token%}
                                    {{form|crispy}}
                                </div>
                                <button type="submit" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">Добавить</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
              <div class="u-container-style u-layout-cell u-right-cell u-size-30 u-layout-cell-2">
                <div class="u-container-layout u-container-layout-7">
                  <div class="u-align-center u-expanded-width u-opacity u-opacity-50 u-shape u-shape-svg u-text-palette-2-light-2 u-shape-1">
                    <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 160 150" style="">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-8e3a"></use>
                    </svg>
                    <svg class="u-svg-content" viewBox="0 0 160 150" x="0px" y="0px" id="svg-8e3a">
                        <path d="M43.2,126.9c14.2,1.3,27.6,7,39.1,15.6c8.3,6.1,19.4,10.3,32.7,5.3c11.7-4.4,18.6-17.4,21-30.2c2.6-13.3,8.1-25.9,15.7-37.1
	c8.3-12.1,10.8-27.9,5.3-42.7C150.5,20.3,134.6,9,117,7.6C107.9,6.9,98.8,5,90.1,1.9C83-0.6,75-0.7,67.4,2.1
	c-9.9,3.7-17,11.6-20.1,21c-3.3,10.1-10.9,18-20.6,22.2c-0.1,0-0.1,0.1-0.2,0.1c-20.3,8.9-31,32-24.6,53.2
	C6.9,115.6,25.2,125.2,43.2,126.9z"></path>
                    </svg>
                  </div>
                    {% if meal.photo %}
                    <img class="u-border-no-bottom u-border-no-left u-border-no-right u-border-no-top u-image u-image-contain u-image-default u-image-1" src="{{ meal.photo|thumbnail_url:'image' }}" alt="" >
                    {% else %}
                    <img class="u-border-no-bottom u-border-no-left u-border-no-right u-border-no-top u-image u-image-contain u-image-default u-image-1" data-image-width="1000" data-image-height="753" src="{% static 'images/rrrr-min.png'%}">
                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/meals/list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/meals/meals.css' %}" media="screen">
{% endblock %}
{% block scripts %}

{% endblock %}

{% block content %}

    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
      <div class="u-clearfix u-layout-wrap u-layout-wrap-1">
        <div class="u-layout">
          <div class="u-layout-row">
            <div class="u-align-left u-container-style u-layout-cell u-shape-rectangle u-size-15 u-layout-cell-1">
              <div class="u-container-layout u-container-layout-1">
                  <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-1">
                      <div class="u-align-center u-valign-middle u-content-layout u-container-layout u-container-layout-2">
                          <a href="{% url 'meals:create' %}" class="u-align-center u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-1">+ НОВОЕ БЛЮДО</a>
                      </div>
                  </div>
                <div class="u-container-style u-expanded-width u-group u-shape-rectangle u-group-2">
                  <div class="u-container-layout u-valign-middle u-container-layout-3">
                    <form action="{% url 'meals:list' %}" method="get" class="u-border-1 u-border-grey-30 u-search u-search-left u-white u-search-1">
                      <button class="u-search-button" type="submit">
                        <span class="u-search-icon u-spacing-10">
                          <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 56.966 56.966"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-eec0"></use></svg>
                          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-eec0" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" class="u-svg-content"><path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path></svg>
                        </span>
                      </button>
                      <input class="u-search-input" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search">
                    </form>
                  </div>
                </div>
                <div class="u-align-left u-container-style u-expanded-width u-group u-shape-rectangle u-group-3">
                  <div class="u-container-layout u-valign-middle u-container-layout-4">
                    <h5><a href = "{% url 'meals:list' %}"class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">Все блюда</a></h5>
                      {% for cat in cats %}
                          <div>
                              <h5><a href = "{% url 'meals:list' %}?category={{ cat.slug }}" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">{{ cat.name}}</a></h5>
                          </div>
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
            <div class="u-container-style u-layout-cell u-shape-rectangle u-size-45 u-layout-cell-2">
              <div class="u-container-layout u-container-layout-5">
                <div class="u-expanded-width u-list u-list-1">
                  <div class="u-repeater u-repeater-2">
                      {%  for meal in meals %}
                    <div class="u-align-justify u-border-2 u-border-grey-75 u-container-style u-list-item u-radius-27 u-repeater-item u-shape-round u-list-item-1">
                        <div class="u-align-center u-container-layout u-similar-container u-container-layout-6">
                            <span class="u-file-icon u-icon u-text-custom-color-2 u-icon-1">
                                <img src="{%  static 'images/9.png' %}" alt="">
                            </span>
                          <h5 class="u-align-center u-text u-text-2">{{ meal.name}}</h5>
                          <a href="{% url 'meals:add_to_day' meal.slug %}" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">+ в меню</a>
                          <a href="{% url 'meals:detail' meal.slug %}" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">просмотреть</a>
                      </div>
                    </div>
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


{#    Paginator#}
{#    <div class="pager">#}
{#        <span >#}
{#            {% if page_obj.has_previous %}#}
{#                <a href="?page=1">&laquo; first</a>#}
{#                <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
{#            {% endif %}#}
{#            <span class="current">#}
{#                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}#}
{#            </span>#}
{#            {% if page_obj.has_next %}#}
{#                <a href="?page={{ page_obj.next_page_number }}">next</a>#}
{#                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
{#            {% endif %}#}
{#        </span>#}
{#    </div>#}


{% endblock %}