cookingplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('users/', include('users.urls')),
    path('', include('menu.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/urls.py
from django.urls import path

from .views import MealCreateView, MealDetailView, MealsList, MealUpdateView, MealDeleteView, AddMealToDay, \
    AddIngredientsToMeal, MealIngredientsDeleteView

app_name = 'meals'

urlpatterns = [
    path('list/', MealsList.as_view(), name='list'),
    path('create/', MealCreateView.as_view(), name='create'),
    path('<slug:slug>/detail/', MealDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', MealUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', MealDeleteView.as_view(), name='delete'),
    path('<slug:slug>/add_to_day/', AddMealToDay.as_view(), name='add_to_day'),
    path('<slug:slug>/add_ingredients/', AddIngredientsToMeal.as_view(), name='add_ingredients'),
    path('<slug:slug>/delete_ingredient/<int:pk>', MealIngredientsDeleteView.as_view(), name='delete_ingredient'),
]

menu/urls.py
from django.urls import path

from .views import index, DayDeleteView, DayListView, DayCreateView, BreakfastCreateView, LaunchCreateView, \
    DinnerCreateView, ShoppingListView

app_name = 'menu'

urlpatterns = [
    path('', index, name='index'),
    path('list/', DayListView.as_view(), name='list'),
    path('create/', DayCreateView.as_view(), name='create'),
    path('<slug:slug>/create/breakfast', BreakfastCreateView.as_view(), name='create_breakfast'),
    path('<slug:slug>/create/launch', LaunchCreateView.as_view(), name='create_launch'),
    path('<slug:slug>/create/dinner', DinnerCreateView.as_view(), name='create_dinner'),
    path('<slug:slug>/delete/', DayDeleteView.as_view(), name='delete'),
    path('', ShoppingListView.as_view(), name='shopping_list'),

]

users/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view, OnlyForAuthenticatedUsersView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('secured/', OnlyForAuthenticatedUsersView.as_view(), name='secured')
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="description" content="">
    <title>{{ title }}</title>

      <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
      <link rel="stylesheet" href="{% static 'css/base.css' %}" media="screen">
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="screen">
      <link rel="stylesheet" href="{% static 'css/index.css' %}" media="screen">

      {% block links %}{% endblock %}

      <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
      <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
      {% block scripts %}{% endblock %}


    <meta name="generator" content="Nicepage 4.12.14, nicepage.com">

    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"logo": "images/horizontal_on_white_by_logaster1.png"}
    </script>

    <meta name="theme-color" content="#666ca7">
    <meta property="og:title" content="Главная">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body u-xl-mode">

    <header class="u-clearfix u-header" id="sec-643f" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
          <div class="u-container-style u-group u-group-1">
              <div class="u-container-layout u-container-layout-1">
                  <a href="/" class="u-image u-logo u-image-1" data-image-width="220" data-image-height="100">
                      <img src="{% static 'images/horizontal_on_white_by_logaster1.png' %}" class="u-logo-image u-logo-image-1">
                  </a>
                  <div class="u-container-style u-group u-group-2">
                      <div class="u-container-layout u-container-layout-2">
                          {% if request.user.is_authenticated %}
                              <div class="u-layout-row">
                                  <div class="u-container-style u-layout-cell u-size-30 u-layout-cell-3">
                                      <div class="u-container-layout u-container-layout-3">
                                          <p class="u-align-left u-text u-text-custom-color-2 u-text-default u-text-1">Welcome, {{ request.user.username }}</p>
                                      </div>
                                  </div>
                                  <div class="u-container-style u-layout-cell u-size-30 u-layout-cell-4">
                                      <div class="u-container-layout  u-container-layout-4">
                                          <a class="u-align-right u-text u-text-custom-color-2 u-text-default u-text-2" href="{% url 'users:logout' %}" >Logout</a>
                                      </div>
                                  </div>
                              </div>
                            {% else %}
                              <div class="u-layout-row">
                                  <div class="u-container-style u-layout-cell u-size-30 u-layout-cell-3">
                                      <div class="u-container-layout u-container-layout-3">
                                          <a class="u-align-left u-text u-text-custom-color-2 u-text-default u-text-1" href="{% url 'users:login' %}" >Login</a>
                                      </div>
                                  </div>
                                  <div class="u-container-style u-layout-cell u-size-30 u-layout-cell-4">
                                      <div class="u-container-layout u-container-layout-4">
                                          <a class="u-align-right u-text u-text-custom-color-2 u-text-default u-text-2" href="{% url 'users:register' %}">Registration</a>
                                      </div>
                                  </div>
                              </div>
                          {% endif %}
                      </div>
                  </div>
              </div>
          </div>
          <nav class="u-align-right u-menu u-menu-dropdown u-offcanvas u-menu-1" data-responsive-from="XL">
              <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700;">
                  <a class="u-button-style u-custom-border u-custom-border-color u-custom-borders u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#" style="padding: 6px 8px; font-size: calc(1em + 12px);">
                      <svg class="u-svg-link" viewBox="0 0 24 24">
                          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use>
                      </svg>
                      <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
                          <g>
                              <rect y="1" width="16" height="2"></rect>
                              <rect y="7" width="16" height="2"></rect>
                              <rect y="13" width="16" height="2"></rect>
                          </g>
                      </svg>
                  </a>
              </div>
              <div class="u-nav-container">
                  <ul class="u-nav u-spacing-20 u-unstyled u-nav-1">
                      <li class="u-nav-item">
                          <a class="u-button-style u-nav-link u-text-active-palette-2-base u-text-grey-90 u-text-hover-palette-2-base" href="/" style="padding: 10px;">Главная</a>
                      </li>
                      <li class="u-nav-item">
                          <a class="u-button-style u-nav-link u-text-active-palette-2-base u-text-grey-90 u-text-hover-palette-2-base" href="{% url 'meals:list' %}" style="padding: 10px;">Рецепты</a>
                      </li>
                      <li class="u-nav-item">
                          <a class="u-button-style u-nav-link u-text-active-palette-2-base u-text-grey-90 u-text-hover-palette-2-base" href="{% url 'menu:list' %}" style="padding: 10px;">Меню</a>
                      </li>
                  </ul>
              </div>
              <div class="u-nav-container-collapse">
                  <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                      <div class="u-inner-container-layout u-sidenav-overflow">
                          <div class="u-menu-close">
                          </div>
                          <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                              <li class="u-nav-item">
                                  <a class="u-button-style u-nav-link" href="/">Главная</a>
                              </li>
                              <li class="u-nav-item">
                                  <a class="u-button-style u-nav-link" href="{% url 'meals:list' %}">Рецепты</a>
                              </li>
                              <li class="u-nav-item">
                                  <a class="u-button-style u-nav-link" href="{% url 'menu:list' %}">Меню</a>
                              </li>
                          </ul>
                      </div>
                  </div>
                  <div class="u-black u-menu-overlay u-opacity u-opacity-70">
                  </div>
              </div>
          </nav>
      </div>
  </header>

 {% block content %}{% endblock %}

  <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-a5d5">
      <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">create by TetianaZhuk</p>
      </div>
  </footer>


  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}

    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-align-center u-container-style u-layout-cell u-shape-rectangle u-size-30 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <h5 class="u-custom-font u-font-montserrat u-text u-text-default u-text-1">У тебя всегда есть план :)</h5>
                  <div class="u-expanded-width-lg u-opacity u-opacity-45 u-shape u-shape-svg u-text-palette-2-light-2 u-shape-1">
                    <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 160 160" style="">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-9c5e"></use>
                    </svg>
                    <svg class="u-svg-content" viewBox="0 0 160 160" x="0px" y="0px" id="svg-9c5e" style="enable-background:new 0 0 160 160;">
                        <path d="M151.7,132.5c-3.4,6-7.9,11.7-13.3,16.5c-29.2,26.1-54.1-2.3-88.2-3S0,109.5,0,91.6s14.8-31.3,25.3-45.3S33.4,11,51.8,3
	c15.3-6.6,33.6-0.4,51.6,0.7c11.2,0.7,28.8-3.8,38.2,0.4s11.8,15.4,9.2,22.8c-1.9,5.4-5.5,11.6-12.8,16.5
	c-9.3,10.1-4.7,22.9,3.7,33.4c7.8,9.7,17.7,11.7,18.3,23.5C160.4,110.8,157.6,122.2,151.7,132.5L151.7,132.5z"></path>
                    </svg>
                  </div>
                  <img class="u-image u-image-contain u-image-default u-image-1" src="{% static 'images/566-min.png' %}" alt="" data-image-width="900" data-image-height="821">
{#                  <h2 class="u-custom-font u-font-montserrat u-text u-text-custom-color-2 u-text-2"> cooking​Plan</h2>#}
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-shape-rectangle u-size-30 u-layout-cell-2">
                <div class="u-container-layout u-valign-middle u-container-layout-2">
                  <div class="u-expanded-width u-list u-list-1">
                      <div class="u-repeater u-repeater-1">
                          <a href="{% url 'meals:list' %}">
                            <div class="u-align-left u-border-2 u-border-white u-container-style u-list-item u-repeater-item u-list-item-1">
                                <div class="u-container-layout u-similar-container u-container-layout-3">
                                    <span class="u-custom-color-2 u-file-icon u-icon u-icon-circle u-icon-1">
                                        <img src="{% static 'images/5.png' %}" alt="">
                                    </span>
                                    <h6 class="u-align-center u-custom-font u-font-montserrat u-text u-text-default u-text-3">Рецепты</h6>
                                    <p class="u-text u-text-grey-40 u-text-4">Добавляй свои рецепты или используй существующие.</p>
                                </div>
                            </div>
                          </a>
                          <a href="{% url 'menu:list' %}">
                            <div class="u-align-left u-border-2 u-border-white u-container-style u-list-item u-repeater-item u-list-item-2">
                                <div class="u-container-layout u-similar-container u-container-layout-4">
                                    <span class="u-custom-color-2 u-file-icon u-icon u-icon-circle u-icon-2">
                                        <img src="{% static 'images/6.png' %}" alt="">
                                    </span>
                                    <h6 class="u-align-center u-custom-font u-font-montserrat u-text u-text-default u-text-5"> Меню</h6>
                                    <p class="u-text u-text-grey-40 u-text-6">Планируй и просматривай меню за любой период</p>
                                </div>
                            </div>
                          </a>
                          <a href="">
                            <div class="u-align-left u-border-2 u-border-white u-container-style u-list-item u-repeater-item u-list-item-3">
                                <div class="u-container-layout u-similar-container u-container-layout-5">
                                    <span class="u-custom-color-2 u-file-icon u-icon u-icon-circle u-icon-3">
                                        <img src="{% static 'images/7.png' %}" alt="">
                                    </span>
                                    <h6 class="u-align-center u-custom-font u-font-montserrat u-text u-text-default u-text-7"> Список покупок</h6>
                                    <p class="u-text u-text-grey-40 u-text-8">Составляй список покупок на основании запланированного меню</p>
                                </div>
                            </div>
                          </a>
                        </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}