cookingplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('users/', include('users.urls')),
    path('', include('menu.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path

from .views import index, DayDeleteView, DayListView, DayCreateView, BreakfastCreateView, LaunchCreateView, \
    DinnerCreateView, ShoppingListView

app_name = 'menu'

urlpatterns = [
    path('', index, name='index'),
    path('list/', DayListView.as_view(), name='list'),
    path('create/', DayCreateView.as_view(), name='create'),
    path('<slug:slug>/create/breakfast', BreakfastCreateView.as_view(), name='create_breakfast'),
    path('<slug:slug>/create/launch', LaunchCreateView.as_view(), name='create_launch'),
    path('<slug:slug>/create/dinner', DinnerCreateView.as_view(), name='create_dinner'),
    path('<slug:slug>/delete/', DayDeleteView.as_view(), name='delete'),
    path('', ShoppingListView.as_view(), name='shopping_list'),

]

menu/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from meals.models import Meal


class Day(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    date = models.DateField()
    slug = models.SlugField(max_length=10, unique=True, verbose_name='URL')

    breakfast = models.ForeignKey(Meal,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True,
                                  related_name='breakfast')
    launch = models.ForeignKey(Meal,
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True,
                               related_name='launch')
    dinner = models.ForeignKey(Meal,
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True,
                               related_name='dinner')

    class Meta:
        unique_together = ('author', 'date')
        ordering = ['-date']

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.date.strftime("%Y-%m-%d"))
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('menu:detail', kwargs={'slug': self.slug})

menu/forms.py
import datetime

from django import forms

from menu.models import Day


class DayForm(forms.ModelForm):
    class Meta:
        model = Day
        exclude = ('author', 'slug',)


class BreakfastForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = ('breakfast',)


class LaunchForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = ('launch',)


class DinnerForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = ('dinner',)


class DateForm(forms.Form):
    start_date = datetime.date.today()
    end_date = datetime.date.today() + datetime.timedelta(weeks=1)
    start = forms.DateField(widget=forms.SelectDateWidget, label='Введите начальную дату', initial=start_date)
    end = forms.DateField(widget=forms.SelectDateWidget, label='Введите конечную дату', initial=end_date)

menu/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
import datetime

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.views.generic.edit import FormMixin, DeleteView

from ingredients.models import Ingredient

from menu.forms import DateForm, BreakfastForm, LaunchForm, DinnerForm
from menu.models import Day


def index(request):
    template_name = 'index.html'
    context = {'title': 'Главная'}
    return render(request, template_name, context)


class DayListView(ListView):
    model = Day
    template_name = 'menu/list.html'
    context_object_name = 'days'


class DayCreateView(CreateView, FormMixin):
    model = Day
    fields = '__all__'
    template_name = 'menu/create.html'
    context_object_name = 'days'
    success_url = 'menu:list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = DateForm()
        return context

    def post(self, request, *args, **kwargs):
        form = DateForm(self.request.POST)
        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, **kwargs):
        start = form.cleaned_data['start']
        end = form.cleaned_data['end']
        while start <= end:
            try:
                Day.objects.get(date=start, author=self.request.user)
            except Day.DoesNotExist:
                Day.objects.create(date=start, author=self.request.user)
            start += datetime.timedelta(days=1)
        return redirect("menu:list")


class LaunchCreateView(LoginRequiredMixin, CreateView):
    model = Day
    template_name = 'menu/create_day.html'
    form_class = LaunchForm
    success_url = reverse_lazy('menu:list')


class DinnerCreateView(CreateView):
    model = Day
    template_name = 'menu/create_day.html'
    form_class = DinnerForm
    success_url = reverse_lazy('menu:list')


class BreakfastCreateView(CreateView):
    model = Day
    template_name = 'menu/create_day.html'
    form_class = BreakfastForm
    success_url = reverse_lazy('menu:list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, **kwargs):
        day = Day.objects.get(slug=kwargs['slug'])
        day.breakfast = form.cleaned_data['breakfast']
        day.save()
        return redirect("menu:list")


class LaunchCreateView(CreateView):
    model = Day
    template_name = 'menu/create_day.html'
    form_class = LaunchForm
    success_url = reverse_lazy('menu:list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, **kwargs):
        day = Day.objects.get(slug=kwargs['slug'])
        day.launch = form.cleaned_data['launch']
        day.save()
        return redirect("menu:list")


class DinnerCreateView(CreateView):
    model = Day
    template_name = 'menu/create_day.html'
    form_class = DinnerForm
    success_url = reverse_lazy('menu:list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, **kwargs):
        day = Day.objects.get(slug=kwargs['slug'])
        day.dinner = form.cleaned_data['dinner']
        day.save()
        return redirect('menu:list')


class DayDeleteView(DeleteView):
    model = Day
    template_name = 'menu/list.html'
    success_url = reverse_lazy('menu:list')


class ShoppingListView(ListView):
    model = Ingredient
    template_name = 'menu/list.html'
    context_object_name = 'shopping_list'

templates/menu/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block content %}
    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
        <div class="u-clearfix u-sheet u-sheet-1">
            <title> {{title}} </title>
            <form method="post" enctype="multipart/form-data" action="">
                <div>
                    {%csrf_token%}
                    {{ form|crispy }}
                </div>
                <button class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-6 u-btn-1" type="submit">Создать</button>
            </form>
        </div>
    </section>
{% endblock %}

templates/menu/create_day.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{#{% block links %}#}
{#<link rel="stylesheet" href="{% static 'css/menu/menu.css' %}" media="screen">#}
{#{% endblock %}#}

{% block content %}
    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
        <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
                <form method="post" enctype="multipart/form-data" action="">
                    <div>
                        {%csrf_token%}
                        {{ form|crispy }}
                    </div>
                    <button type="submit">Выбрать</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/menu/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        Дата:
        <br>
        {{ day.date }}
        <br>
    <table>
        <tr>
            <th>Завтрак</th>
            <th>Обед</th>
            <th>Ужин</th>
        </tr>
        <tr>
            <td>
                {% if day.breakfast %}
                    {{ day.breakfast }}
                {% else %}
                    <p>Блюдо не выбрано</p>
                {% endif %}
            </td>
            <td>
                {% if day.launch %}
                    {{ day.launch }}
                {% else %}
                    <p>Блюдо не выбрано</p>
                {% endif %}
            </td>
            <td>
                {% if day.dinner %}
                    {{ day.dinner }}
                {% else %}
                    <p>Блюдо не выбрано</p>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>
                {{ day_detail_form.breakfast }}
            </td>
            <td>
                {{ day_detail_form.launch }}
            </td>
            <td>
                {{ day_detail_form.dinner }}
            </td>
        </tr>
    </table>
        <button type="submit">Сохранить</button>
    </form>



{% endblock %}

templates/menu/form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{#{% block links %}#}
{#<link rel="stylesheet" href="{% static 'css/menu/menu.css' %}" media="screen">#}
{#{% endblock %}#}

{% block content %}
    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
        <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
                <div class="u-layout">
                    <div class="u-layout-row">
                        <div class="u-align-center u-container-style u-layout-cell u-shape-rectangle u-size-30 u-layout-cell-1">
                            <div class="u-container-layout u-container-layout-1">
                                <div class="u-expanded-width-lg u-opacity u-opacity-45 u-shape u-shape-svg u-text-palette-2-light-2 u-shape-1">
                                    <div class="">
                                        <form action="#" method="POST">
                                            {%csrf_token%}
                                            {{ form|crispy }}
                                            <button type="submit">Выбрать</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="u-container-style u-layout-cell u-shape-rectangle u-size-30 u-layout-cell-2">
                            <div class="u-container-layout u-container-layout-2">
                                <div class="u-expanded-width u-list u-list-1">
                                    <div class="u-repeater u-repeater-1">
                                        {% for meal in meals %}
                                            <div class="u-align-left u-border-2 u-border-white u-container-style u-list-item u-repeater-item u-list-item-1">
                                            <div class="u-container-layout u-similar-container u-container-layout-3">
                                                <span class="u-file-icon u-icon u-icon-2">
                                                    <img src="{% static 'images/868070.png' %}" alt="">
                                                </span>
                                                <p class="u-text u-text-grey-40 u-text-2">{{ meal.name}}</p>
                                            </div>
                                        {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/menu/list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/menu/menu.css' %}" media="screen">
{% endblock %}

{% block content %}

    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
        <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
                <div class="u-layout">
                    <div class="u-layout-row">
                        <div class="u-container-style u-layout-cell u-shape-rectangle u-size-15 u-layout-cell-1">
                            <div class="u-container-layout u-container-layout-1">
                                <div class="u-align-center u-container-style u-group u-group-1">
                                    <form method="post" action="" class="u-container-layout u-container-layout-2">
                                        {% csrf_token %}
                                        {{ date_form|crispy }}
{#                                        <button  class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-6 u-btn-1" type="submit">ПРОСМОТРЕТЬ</button>#}
                                        <a  class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-6 u-btn-2"  href="">В список покупок</a>
                                        <a href="{% url 'menu:create' %}" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-6 u-btn-1">Создать</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="u-container-style u-layout-cell u-shape-rectangle u-size-45 u-layout-cell-2">
                            <div class="u-container-layout u-container-layout-4">
                                {% for day in days %}
                                <div class="u-container-style u-expanded-width u-group u-group-3">
                                    <div class="u-container-layout u-container-layout-5">
                                        <h4 class="u-text u-text-default u-text-3">
                                                {{ day.date|date:'l'}}
                                                {{ day.date|date:'d'}}
                                                {{ day.date|date:'F'}} {{ day.date|date:'Y'}}
                                        </h4>


                                        <form method="post" action="{% url 'menu:delete' day.slug %}">
                                            {% csrf_token %}
                                           <button  class="u-active-none u-border-1 u-border-active-palette-1-light-1 u-border-hover-palette-1-light-1 u-border-palette-1-dark-2 u-btn u-button-style u-hover-none u-none u-text-active-palette-2-base u-text-custom-color-2 u-text-hover-palette-2-base u-btn-4" type="submit">Удалить</button>
                                        </form>

                                        <div class="u-list u-list-1">
                                            <div class="u-align-center u-repeater u-repeater-1">
                                                <div class="u-align-center u-border-9 u-border-custom-color-2 u-border-no-bottom u-border-no-left u-border-no-right u-container-style u-list-item u-radius-50 u-repeater-item u-shape-round u-video-cover u-white u-list-item-1" data-animation-name="customAnimationIn" data-animation-duration="1750" data-animation-direction="" data-animation-delay="250">
                                                    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-6">
                                                        <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">Завтрак</h4>
                                                        <span class="u-file-icon u-icon u-icon-2">
                                                            <img src="{% static 'images/868070.png' %}" alt="">
                                                        </span>
                                                            {% if day.breakfast %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">{{ day.breakfast.name }}</h4>
                                                            {% else %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">Блюдо не выбрано</h4>
                                                            {% endif %}
                                                    <a href="{% url 'menu:create_breakfast' day.slug %}" class="u-active-none u-border-1 u-border-active-palette-1-light-1 u-border-hover-palette-1-light-1 u-border-palette-1-dark-2 u-btn u-button-style u-hover-none u-none u-text-active-palette-2-base u-text-custom-color-2 u-text-hover-palette-2-base u-btn-4">Изменить</a>
                                                    </div>
                                                </div>
                                                <div class="u-align-center u-border-9 u-border-custom-color-2 u-border-no-bottom u-border-no-left u-border-no-right u-container-style u-list-item u-radius-50 u-repeater-item u-shape-round u-video-cover u-white u-list-item-2" data-animation-name="customAnimationIn" data-animation-duration="1750" data-animation-direction="" data-animation-delay="250">
                                                    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-7">
                                                        <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-5"> Обед</h4>
                                                        <span class="u-file-icon u-icon u-icon-2">
                                                            <img src="{% static 'images/868070.png' %}" alt="">
                                                        </span>
                                                        {% if day.launch %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">{{ day.launch.name }}</h4>
                                                        {% else %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">Блюдо не выбрано</h4>
                                                        {% endif %}
                                                    <a href="{% url 'menu:create_launch' day.slug %}" class="u-active-none u-border-1 u-border-active-palette-1-light-1 u-border-hover-palette-1-light-1 u-border-palette-1-dark-2 u-btn u-button-style u-hover-none u-none u-text-active-palette-2-base u-text-custom-color-2 u-text-hover-palette-2-base u-btn-4">Изменить</a>
                                                    </div>
                                                </div>
                                                <div class="u-align-center u-border-9 u-border-custom-color-2 u-border-no-bottom u-border-no-left u-border-no-right u-container-style u-list-item u-radius-50 u-repeater-item u-shape-round u-video-cover u-white u-list-item-3" data-animation-name="customAnimationIn" data-animation-duration="1750" data-animation-direction="" data-animation-delay="250">
                                                    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-8">
                                                        <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-6"> Ужин</h4>
                                                        <span class="u-file-icon u-icon u-icon-2">
                                                            <img src="{% static 'images/868070.png' %}" alt="">
                                                        </span>
                                                        {% if day.dinner %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">{{ day.dinner.name }}</h4>
                                                        {% else %}
                                                            <h4 class="u-custom-font u-font-montserrat u-text u-text-default u-text-4">Блюдо не выбрано</h4>
                                                        {% endif %}
                                                    <a href="{% url 'menu:create_dinner' day.slug %}" class="u-active-none u-border-1 u-border-active-palette-1-light-1 u-border-hover-palette-1-light-1 u-border-palette-1-dark-2 u-btn u-button-style u-hover-none u-none u-text-active-palette-2-base u-text-custom-color-2 u-text-hover-palette-2-base u-btn-4">Изменить</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

templates/menu/recepies.html
    <section class="u-align-center u-clearfix u-section-1" id="sec-886c">
      <div class="u-clearfix u-layout-wrap u-layout-wrap-1">
        <div class="u-layout">
          <div class="u-layout-row">
            <div class="u-container-style u-layout-cell u-shape-rectangle u-size-60 u-layout-cell-1">
              <div class="u-container-layout u-container-layout-1">
                <div class="u-expanded-width u-list u-list-1">
                  <div class="u-repeater u-repeater-1"></div>
                </div>
                <div class="u-container-style u-expanded-width u-group u-group-1">
                  <div class="u-container-layout u-container-layout-2">
                    <div class="u-align-left u-container-style u-expanded-width u-group u-group-2">
                      <div class="u-container-layout u-container-layout-3">
                        <div class="u-align-center u-container-style u-group u-shape-rectangle u-group-3">
                          <div class="u-container-layout u-container-layout-4">
                            <a href="https://nicepage.online" class="u-align-center u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-1">+ НОВОЕ БЛЮДО</a>
                          </div>
                        </div>
                        <div class="u-container-style u-group u-shape-rectangle u-group-4">
                          <div class="u-container-layout u-container-layout-5">
                            <form action="#" method="get" class="u-align-center u-border-1 u-border-grey-30 u-search u-search-left u-white u-search-1">
                              <button class="u-search-button" type="submit">
                                <span class="u-search-icon u-spacing-10">
                                  <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 56.966 56.966"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-eec0"></use></svg>
                                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-eec0" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" class="u-svg-content"><path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path></svg>
                                </span>
                              </button>
                              <input class="u-search-input" type="search" name="search" value="" placeholder="Search">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="u-align-left u-container-style u-expanded-width u-group u-shape-rectangle u-group-5">
                      <div class="u-container-layout u-valign-middle u-container-layout-6">
                        <ul class="u-text u-text-default u-text-1">
                          <li>Пример элемента 1</li>
                          <li>Пример элемента 2</li>
                          <li>Пример элемента 3</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="u-list u-list-2">
                  <div class="u-repeater u-repeater-2">
                    <div class="u-border-2 u-border-grey-75 u-container-style u-list-item u-radius-27 u-repeater-item u-shape-round u-list-item-1">
                      <div class="u-container-layout u-similar-container u-container-layout-7"><span class="u-file-icon u-icon u-text-custom-color-2 u-icon-1"><img src="images/9.png" alt=""></span>
                        <h3 class="u-align-center u-text u-text-2">Название блюда</h3>
                        <a href="https://nicepage.com/k/shopping-cart-html-templates" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-2">+ в меню</a>
                      </div>
                    </div>
                    <div class="u-align-center u-border-2 u-border-grey-75 u-container-style u-list-item u-radius-27 u-repeater-item u-shape-round u-list-item-2">
                      <div class="u-container-layout u-similar-container u-container-layout-8"><span class="u-file-icon u-icon u-text-custom-color-2 u-icon-2"><img src="images/9.png" alt=""></span>
                        <h3 class="u-align-center u-text u-text-3">Название блюда</h3>
                        <a href="https://nicepage.com/k/shopping-cart-html-templates" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-3">Кнопка</a>
                      </div>
                    </div>
                    <div class="u-border-2 u-border-grey-75 u-container-style u-list-item u-radius-27 u-repeater-item u-shape-round u-list-item-3">
                      <div class="u-container-layout u-similar-container u-container-layout-9"><span class="u-file-icon u-icon u-text-custom-color-2 u-icon-3"><img src="images/9.png" alt=""></span>
                        <h3 class="u-align-center u-text u-text-4">Название блюда</h3>
                        <a href="https://nicepage.com/k/shopping-cart-html-templates" class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-50 u-btn-4">Кнопка</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

templates/menu/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="u-layout-row">
        <div class="u-container-style u-layout-cell u-shape-rectangle u-size-15 u-layout-cell-1">
            <div class="u-container-layout u-container-layout-1">
                <div class="u-align-center u-container-style u-group u-group-1">
                    <form method="post" action="" class="u-container-layout u-container-layout-2">
                        {% csrf_token %}
                        {{ day_detail_form|crispy }}
                        <button  class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-1 u-radius-6 u-btn-1" type="submit">сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}